#ifdef __cplusplus
extern "C" {
#endif
//=========================================================

// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __INIT_DEVICE_H__
#define __INIT_DEVICE_H__

// USER CONSTANTS
// USER PROTOTYPES

// $[Mode Transition Prototypes]
extern void enter_DefaultMode_from_RESET(void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
extern void HFXO_enter_DefaultMode_from_RESET(void);
extern void LFXO_enter_DefaultMode_from_RESET(void);
extern void CMU_enter_DefaultMode_from_RESET(void);
extern void ADC0_enter_DefaultMode_from_RESET(void);
extern void ACMP0_enter_DefaultMode_from_RESET(void);
extern void IDAC0_enter_DefaultMode_from_RESET(void);
extern void RTC_enter_DefaultMode_from_RESET(void);
extern void USART1_enter_DefaultMode_from_RESET(void);
extern void LEUART0_enter_DefaultMode_from_RESET(void);
extern void VCMP_enter_DefaultMode_from_RESET(void);
extern void WDOG_enter_DefaultMode_from_RESET(void);
extern void I2C0_enter_DefaultMode_from_RESET(void);
extern void TIMER0_enter_DefaultMode_from_RESET(void);
extern void TIMER1_enter_DefaultMode_from_RESET(void);
extern void PCNT0_enter_DefaultMode_from_RESET(void);
extern void PRS_enter_DefaultMode_from_RESET(void);
extern void PORTIO_enter_DefaultMode_from_RESET(void);
// [Config(Per-Module Mode)Transition Prototypes]$

// $[User-defined pin name abstraction]

#define I2C0_SCL_PIN        (13)
#define I2C0_SCL_PORT       (gpioPortE)

#define I2C0_SDA_PIN        (12)
#define I2C0_SDA_PORT       (gpioPortE)

#define LED0_PIN            (11)
#define LED0_PORT           (gpioPortC)

#define LED1_PIN            (10)
#define LED1_PORT           (gpioPortC)

#define PB0_PIN             (9)
#define PB0_PORT            (gpioPortC)

#define PB1_PIN             (8)
#define PB1_PORT            (gpioPortC)

#define RF24_CE_PIN         (0)
#define RF24_CE_PORT        (gpioPortA)

#define RF24_IRQ_PIN        (11)
#define RF24_IRQ_PORT       (gpioPortB)

#define USART1_CLK_PIN      (15)
#define USART1_CLK_PORT     (gpioPortC)

#define USART1_CS_PIN       (14)
#define USART1_CS_PORT      (gpioPortC)

#define USART1_RX_PIN       (6)
#define USART1_RX_PORT      (gpioPortD)

#define USART1_TX_PIN       (7)
#define USART1_TX_PORT      (gpioPortD)

// [User-defined pin name abstraction]$

#endif

#ifdef __cplusplus
}
#endif
